# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "direnv-unstable-${version}";
  version = "2020-03-17";
  rev = "2e441570750105ba8c2acadbc99494657142bc14";

  goPackagePath = "github.com/Caascad/direnv";

  src = fetchgit {
    inherit rev;
    url = "git@github.com:Caascad/direnv.git";
    sha256 = "0ikmyvd0gvjpqgikgr4x32pj9ba032p0496pcwylfhxjdcr4zbhn";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
