#!/usr/bin/env bash

source_hash() {
  local rcpath=${1/#\~/$HOME}
  local hash=${2}
  local rcfile
  if [[ -d $rcpath ]]; then
    rcpath=$rcpath/.envrc
  fi
  if [[ ! -e $rcpath ]]; then
    log_status "referenced $rcpath does not exist"
    return 1
  fi
  rchash=$(shasum -t "$rcpath" | cut -d \  -f 1)
  if [[ "$hash" != "$rchash" ]]; then
    log_status "referenced $rcpath has change, please rehash"
    return 1
  fi

  rcfile=$(user_rel_path "$rcpath")
  watch_file "$rcpath"

  pushd "$(pwd 2>/dev/null)" >/dev/null || return 1
  pushd "$(dirname "$rcpath")" >/dev/null || return 1
  if [[ -f ./$(basename "$rcpath") ]]; then
    log_status "loading $rcfile"
    # shellcheck disable=SC1090
    . "./$(basename "$rcpath")"
  else
    log_status "referenced $rcfile does not exist"
  fi
  popd >/dev/null || return 1
  popd >/dev/null || return 1
}


update_hash() {
  while IFD=' ' read -r _ _path hash
  do
    if [[ -d "$_path" ]]; then
      rcpath="$_path/.envrc"
    else
      rcpath="$_path"
    fi
    rchash=$(shasum -t "$rcpath" | cut -d \  -f 1)

    if [[ "$hash" != "$rchash" ]]; then
      echo "referenced $rcpath has change, rehash ?"
      echo "------------------"
      cat "$rcpath"
      echo "------------------"

      sed -i '/source_hash/ s,'"$_path"'.*,'"$_path"' '"$rchash"',' .envrc
    fi

  done <<< "$(grep -E '^source_hash' .envrc)"
}
